### ISSUE TITLE
Listings quellen angaben

### ISSUE THREAD

**Issue by robme91** [robme91/se-nbno-docu#18]
alle codeblöcke sollten als quelle, den datei namen und/oder pfad im projekt paket beinhalten

**Comment by devfoo-one** [comment]
`NPC.interact() Implementierung (NPC.java)`

**Comment by robme91** [comment]
bis auf die nbno datei wird das so übernommen. da sind das keine wirklichen ausschnitte sondern code beispiele ohne referenzdatei.
