### ISSUE TITLE
Bibliographie

### ISSUE THREAD

**Issue by robme91** [robme91/se-nbno-docu#4]
Brauchen wir ne bibliorafie? Ich verstehe das in der main Datei nich so mit den items da. 
Kannte das bishe rnur  mit .bbl Files oder sowas. 
Also da ich bisher nur internetqullen habe, wäre biblatex evtl. besser als bibtex. da gibts son online ding schon vorgegeben. bei bibtex musste ich das damals immer selber anlegen. 
und dann müssen wir gucken wie wir zitieren. bzw. diese indirekten zitate kennzeichnen.
Oder du hast n plan wie das mit dem vorhanden Zeug umzusetzen ist, weil so viele quellen haben wir jetzt auch nicht

**Comment by devfoo-one** [comment]
Ich bin halt auch nur ne externe bib-Datei gewöhnt. Ich hatte gehofft dass es zu Antlr oder zu Slick2D n zitierfähiges Tool-Paper gibt, hab aber noch keins gefunden. Wir sollten trotzdem alle Quellen in ne Bibliographie machen statt als Fußnoten. Ich check das gleich mal aus
