### ISSUE TITLE
Kapitel Architektur nicht kompilierbar

### ISSUE THREAD

**Issue by robme91** [robme91/se-nbno-docu#6]
In dem Architektur kapitel muss ein Fehler drin sein. Nach dem letzten Pull konnte ich die main nicht mehr kompilieren. Nach auskommentieren des architektur kapitels gings wieder. Laut Fehlermeldung eine schließende Klammer oder sowas in Zeile 30 fehlt. Aaber latex fehlermeldungen sind sone sache. vielleicht liegts auch an was anderem

**Comment by devfoo-one** [comment]
Bei mir kompilierts...

**Comment by devfoo-one** [comment]
auch nach dem pullen deines aktuellen Stands

**Comment by devfoo-one** [comment]
Ich hab noch was gefunden in dieser Zeile 30 ... check mal ob das jetzt geht bitte... @robme91

**Comment by robme91** [comment]
Jap jetzt gehts. Danke dir
