### ISSUE TITLE
Code EInbindung gepusht

### ISSUE THREAD

**Issue by robme91** [robme91/se-nbno-docu#7]
Hab auf den Master mal ein paket für Codeeinbindung gepusht. Dabei ist direkt son Java Syntax highlighting, dass man dann verwenden kann. Können ide farben noch umstellen falls gewünscht.

**Comment by robme91** [comment]
evtl. Listings umbenenn in irgendwas anderes? zum beispiel: Code, oder Auszug oder iwas anderes

**Comment by devfoo-one** [comment]
Ich find Listing eigentlich gut.

**Comment by robme91** [comment]
ok gut.
Andere Frage:
Wollen wir Codeblöcke als "minipages" deklarieren immer, so dass sie nicht umbrechen. Sonst passiert es manchmal, das begin des codes auf der einen seite/spalte und der rest auf der nächsten Seite/spalte landet

**Comment by devfoo-one** [comment]
Wees nich, was is denn die Alternative zum Umbruch? Abbruch oder skaliert das?

**Comment by robme91** [comment]
Naja bei minipages werden die blöcke immer als ganzes genommen. heißt, sie werden immer in einer spalte sein und wenn sie da nicht mehr reinpassen vollständig kommen sie auf die nächste

**Comment by devfoo-one** [comment]
Ah oke, ich hatte das falsch verstanden... also mich juckts nich wenn das auf die nächste Spalte rutscht... dieses Paperformat ist doch eh immer wie hingekotzt.

**Comment by devfoo-one** [comment]
aber ich bring auch kaum codebeispiele, weil das wird sonst alles zu umfangreich... du hast mehr code, du entscheidest

**Comment by devfoo-one** [comment]
Oke, lass einfach umbrechen, keine minipage, passt schon.
